#cloud-config

# Copyright (c) 2022 Microsoft Corporation. All rights reserved.
# Software is licensed under the MIT License. See LICENSE in the project
# root for license information.

package_upgrade: true
packages:
    - tigervnc-server
    - python3
    - python3-requests
runcmd:
    - [ yum, "-y", groups, install, "GNOME Desktop" ]
    - [ sudo, curl, "-L", "https://aka.ms/downloadazcopy-v10-linux", "--output", "/tmp/downloadazcopy-v10-linux" ]
    - [ sudo, mkdir, "-p", "/tmp/downloadazcopy" ]
    - [ sudo, tar, "-xvzf", "/tmp/downloadazcopy-v10-linux", "--directory", "/tmp/downloadazcopy" ]
    - [ sudo, rm, "-f", "/usr/bin/azcopy" ]
    - [ sudo, cp, "/tmp/downloadazcopy/azcopy_linux_amd64_10.17.0/azcopy", "/usr/bin/" ]
    - [ sudo, chmod, "755", "/usr/bin/azcopy" ]
