# Copyright (c) 2022 Microsoft Corporation. All rights reserved.
# Software is licensed under the MIT License. See LICENSE in the project
# root for license information.

ARG BUNDLE_DIR
ARG IMAGE_NAME=mcr.microsoft.com/mirror/docker/library/alpine
ARG IMAGE_TAG=3.15

FROM $IMAGE_NAME:$IMAGE_TAG

RUN apk add --update nodejs

WORKDIR /app/

COPY $BUNDLE_DIR/tcp-to-blob-text-canary.js .
