# Copyright (c) 2022 Microsoft Corporation. All rights reserved.
# Software is licensed under the MIT License. See LICENSE in the project
# root for license information.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: tcp-to-blob-text-canary-cron
spec:
  schedule: "50 8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: tcp-to-blob-text-canary
              image: "${ACR_NAME}.azurecr.io/tcp-to-blob-text-canary:latest"
              command: ["node", "tcp-to-blob-text-canary.js"]
              args:
                [
                  '{"host" : "${LB_IP}", "port": ${PORT}, "numLines": ${CANARY_NUM_LINES}}',
                ]
          restartPolicy: OnFailure
