# Copyright (c) 2022 Microsoft Corporation. All rights reserved.
# Software is licensed under the MIT License. See LICENSE in the project
# root for license information.
trailingComma: 'es5'
tabWidth: 4
semi: false
singleQuote: true
insertFinalNewline: true
